RepoMaker/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from maker.views import media_serve
from maker.views.repository import RepositoryListView

urlpatterns = [
    url(r'^$', RepositoryListView.as_view(), name="index"),
    url(r'^repo/', include('maker.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], media_serve,
        {'document_root': settings.MEDIA_ROOT}),
]

if not settings.SINGLE_USER_MODE:
    urlpatterns += [
        url(r'^accounts/', include('allauth.urls')),
    ]

maker/urls.py
from django.conf.urls import url

from maker.models import S3Storage, SshStorage, GitStorage
from maker.views.app import AppAddView, AppDetailView, AppUpdateView, AppDeleteView, \
    AppTranslationUpdateView
from maker.views.gitstorage import GitStorageCreate, GitStorageUpdate, GitStorageDetail, \
    GitStorageDelete
from maker.views.remoterepository import RemoteRepositoryCreateView, RemoteAppCreateView
from maker.views.repository import RepositoryListView, RepositoryCreateView, RepositoryView, \
    RepositoryUpdateView, RepositoryDeleteView
from maker.views.s3storage import S3StorageCreate, S3StorageDetail, S3StorageUpdate, S3StorageDelete
from maker.views.screenshot import ScreenshotCreateView, ScreenshotDeleteView
from maker.views.sshstorage import SshStorageCreate, SshStorageUpdate, SshStorageDetail, \
    SshStorageDelete
from maker.views.apk import ApkUploadView, ApkPointerDeleteView
from . import views


urlpatterns = [
    # Repo
    url(r'^$', RepositoryListView.as_view(), name='index'),
    url(r'^add$', RepositoryCreateView.as_view(), name='add_repo'),
    url(r'^(?P<repo_id>[0-9]+)/$', RepositoryView.as_view(), name='repo'),
    url(r'^(?P<repo_id>[0-9]+)/edit/$', RepositoryUpdateView.as_view(),
        name='edit_repo'),
    url(r'^(?P<repo_id>[0-9]+)/delete/$', RepositoryDeleteView.as_view(),
        name='delete_repo'),

    # Remote Repo
    url(r'^remote/add$', RemoteRepositoryCreateView.as_view(), name='add_remote_repo'),
    url(r'^remote/(?P<remote_repo_id>[0-9]+)/update/$', views.remote_update, name='remote_update'),

    # App
    url(r'^(?P<repo_id>[0-9]+)/app/add/$', AppAddView.as_view(), name='add_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/remote/(?P<remote_repo_id>[0-9]+)/add/$',
        AppAddView.as_view(), name='add_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/add/category/(?P<category_id>[0-9]+)/$',
        AppAddView.as_view(), name='add_app_with_category'),
    url(r'^(?P<repo_id>[0-9]+)/app/remote/(?P<remote_repo_id>[0-9]+)/add/' +
        r'category/(?P<category_id>[0-9]+)/$',
        AppAddView.as_view(), name='add_app_with_category'),
    url(r'^(?P<repo_id>[0-9]+)/app/remote/(?P<remote_repo_id>[0-9]+)/add/(?P<app_id>[0-9]+)$',
        RemoteAppCreateView.as_view(), name='add_remote_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/$', AppDetailView.as_view(), name='app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/edit/$', AppUpdateView.as_view(),
        name='edit_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/delete/$', AppDeleteView.as_view(),
        name='delete_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/translate/$',
        AppTranslationUpdateView.as_view(), name='app_translate'),

    # App Screenshots
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/screenshot/add/$',
        ScreenshotCreateView.as_view(), name='screenshot_add'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/screenshot/(?P<s_id>[0-9]+)/delete/$',
        ScreenshotDeleteView.as_view(), name='screenshot_delete'),

    # Apks
    url(r'^(?P<repo_id>[0-9]+)/app/apk/upload/$', ApkUploadView.as_view(), name='apk_upload'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/apk/(?P<pk>[0-9]+)/delete/$',
        ApkPointerDeleteView.as_view(), name='apk_delete'),

    # Repo Operations
    url(r'^(?P<repo_id>[0-9]+)/update/$$', views.update, name='update'),
    url(r'^(?P<repo_id>[0-9]+)/publish/$$', views.publish, name='publish'),

    # S3 Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/add/$',
        S3StorageCreate.as_view(), name=S3Storage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/$',
        S3StorageDetail.as_view(), name=S3Storage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/edit/$',
        S3StorageUpdate.as_view(), name=S3Storage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/delete/$',
        S3StorageDelete.as_view(), name=S3Storage.delete_url_name),

    # SSH Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/add/$',
        SshStorageCreate.as_view(), name=SshStorage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/$',
        SshStorageDetail.as_view(), name=SshStorage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/edit/$',
        SshStorageUpdate.as_view(), name=SshStorage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/delete/$',
        SshStorageDelete.as_view(), name=SshStorage.delete_url_name),

    # Git Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/git/add/$',
        GitStorageCreate.as_view(), name=GitStorage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/$',
        GitStorageDetail.as_view(), name=GitStorage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/edit/$',
        GitStorageUpdate.as_view(), name=GitStorage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/delete/$',
        GitStorageDelete.as_view(), name=GitStorage.delete_url_name),
]

maker/models/apk.py
import datetime
import logging
import os
import zipfile
from io import BytesIO

import requests
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.files import File
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils import timezone
from fdroidserver import common, update
from fdroidserver.update import get_all_icon_dirs

from maker import tasks
from maker.models.repository import AbstractRepository
from maker.storage import get_apk_file_path, RepoStorage
from .app import Repository, RemoteApp, App


class Apk(models.Model):
    package_id = models.CharField(max_length=255, blank=True)
    file = models.FileField(storage=RepoStorage())
    version_name = models.CharField(max_length=128, blank=True)
    version_code = models.PositiveIntegerField(default=0)
    size = models.PositiveIntegerField(default=0)
    signature = models.CharField(max_length=512, blank=True)
    hash = models.CharField(max_length=512, blank=True)
    hash_type = models.CharField(max_length=32, blank=True)
    added_date = models.DateTimeField(default=timezone.now)
    is_downloading = models.BooleanField(default=False)

    def __str__(self):
        return self.package_id + " " + str(self.version_code) + " " + self.file.name

    def download_async(self, url):
        """
        Downloads the APK file asynchronously if it is still missing.
        """
        if not self.file:
            tasks.download_apk(self.pk, url)

    def download(self, url):
        """
        Starts a blocking download of the APK file if it is still missing
        and then saves it.

        This also updates all pointers and links/copies the file to them.
        """
        if self.file:
            return

        # download and store file
        file_rel_path = get_apk_file_path(self, url.rsplit('/', 1)[-1])
        r = requests.get(url)
        if r.status_code != requests.codes.ok:
            # TODO delete self and ApkPointer when this fails permanently
            r.raise_for_status()
        self.file.save(file_rel_path, BytesIO(r.content), save=True)

        # check if the APK file is valid and delete it if not
        file_abs_path = os.path.join(settings.MEDIA_ROOT, file_rel_path)
        AbstractRepository().get_config()
        apk_info = {'icons_src': {}, 'uses-permission': []}
        try:
            update.scan_apk_aapt(apk_info, file_abs_path)
            if 'packageName' not in apk_info:
                raise common.BuildException('APK has no packageName.')
            apk_path = os.path.join(os.getcwd(), file_abs_path)
            if not common.verify_apk_signature(apk_path):
                raise common.BuildException('Invalid APK.')
        except common.BuildException as e:
            logging.warning('Deleting invalid APK file: %s', e)
            ApkPointer.objects.filter(apk=self).all().delete()
            RemoteApkPointer.objects.filter(apk=self).all().delete()
            self.delete()
            return

        # update apk pointers
        pointers = ApkPointer.objects.filter(apk=self).all()
        for pointer in pointers:
            pointer.link_file_from_apk()
            pointer.repo.update_async()

    @staticmethod
    def from_json(package_info):
        """
        Returns an Apk object created from index v1 JSON package information.

        Attention: This only returns the object, but does not save it.
        """
        apk = Apk(
            package_id=package_info['packageName'],
            version_name=package_info['versionName'],
            size=package_info['size'],
            hash=package_info['hash'],
            hash_type=package_info['hashType'],
            added_date=datetime.datetime.fromtimestamp(package_info['added'] / 1000,
                                                       timezone.utc)
        )
        if 'versionCode' in package_info:
            apk.version_code = package_info['versionCode']
        if 'sig' in package_info:
            apk.signature = package_info['sig']
        return apk

    def delete_if_no_pointers(self):
        apk_pointers_exist = ApkPointer.objects.filter(apk=self).exists()
        remote_apk_pointers_exist = RemoteApkPointer.objects.filter(apk=self).exists()
        if not apk_pointers_exist and not remote_apk_pointers_exist:
            self.delete()


class AbstractApkPointer(models.Model):
    apk = models.ForeignKey(Apk, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.app.__str__() + " - " + str(self.apk.version_code)

    class Meta:
        abstract = True


class ApkPointer(AbstractApkPointer):
    repo = models.ForeignKey(Repository, on_delete=models.CASCADE)
    app = models.ForeignKey(App, on_delete=models.CASCADE, null=True)
    file = models.FileField(upload_to=get_apk_file_path, storage=RepoStorage())

    def __str__(self):
        return super().__str__() + " - " + self.file.name

    def initialize(self):
        """
        Initializes this object based on information retrieved from self.file.
        When done, this object will point to an App from self.repo
        and to a globally stored Apk.

        :return: Instance of HttpResponse in case of error, None otherwise
        """
        try:
            apk_info = self._get_info_from_file()
        except zipfile.BadZipFile as e:
            raise ValidationError(e)

        if apk_info is None:
            raise ValidationError('Invalid APK.')
        self._attach_apk(apk_info)
        self._attach_app(apk_info)
        self.save()

    def _get_info_from_file(self):
        """
        Scans the APK file and returns a dictionary of information.
        It also extracts icons and stores them in the repository on disk.

        :return: A dict of APK information or None
        """
        self.repo.get_config()
        filename = os.path.basename(self.file.name)
        skip, apk_info, _ = update.scan_apk({}, filename, self.repo.get_repo_path(),
                                            common.KnownApks(), False)
        if skip:
            return None
        return apk_info

    def _attach_apk(self, apk_info):
        """
        Attaches either an existing or a new Apk to this object.

        :param apk_info: A dict with information about the APK as returned by get_info_from_file()
        """
        apk_set = Apk.objects.filter(package_id=apk_info['packageName'], hash=apk_info['hash'])
        if apk_set.exists():
            self.apk = apk_set.get()
        else:
            self.apk = Apk.objects.create(
                package_id=apk_info['packageName'],
                version_name=apk_info['versionName'],
                version_code=apk_info['versionCode'],
                size=apk_info['size'],
                signature=apk_info['sig'],
                hash=apk_info['hash'],
                hash_type=apk_info['hashType']
            )

        # hardlink/copy file if it does not exist, yet
        if not self.apk.file:
            source = self.file.name
            target = get_apk_file_path(None, os.path.basename(self.file.name))
            target = self.file.storage.link(source, target)
            self.apk.file.name = target
            self.apk.save()

    def _attach_app(self, apk_info):
        """
        Attaches either an existing or a new App to this object
        and updates app information if this Apk holds more recent information.

        :param apk_info: A dict with information about the APK as returned by get_info_from_file()
        """
        # check if app exists already in repo and if so, get latest version
        latest_version = self.apk.version_code
        try:
            old_app = App.objects.get(repo=self.repo, package_id=self.apk.package_id)
            existing_pointers = ApkPointer.objects.filter(app=old_app)
            for pointer in existing_pointers:
                if pointer.apk.version_code > latest_version:
                    latest_version = pointer.apk.version_code
                if pointer.apk.signature != self.apk.signature:
                    raise ValidationError(
                        'This app \'%s\' already exists in your repo, ' % self.apk.package_id +
                        'but has a different signature.')
            self.app = old_app
        except ObjectDoesNotExist:
            app = App.objects.create(
                repo=self.repo,
                package_id=self.apk.package_id,
            )
            app.save()
            self.app = app

        # apply latest info to the app itself
        if self.apk.version_code == latest_version:
            self.app.name = apk_info['name']
            if not self.app.name:  # if the app has no name, use the package name instead
                self.app.name = self.app.package_id
            # TODO check if the icon will update automatically, if so just set path once above
            if 'icon' in apk_info and apk_info['icon'] is not None:
                icon_path = os.path.join(self.repo.get_repo_path(), "icons-640", apk_info['icon'])
                if os.path.isfile(icon_path):
                    self.app.delete_old_icon()
                    self.app.icon.save(apk_info['icon'], File(open(icon_path, 'rb')), save=False)
            self.app.save()

    def link_file_from_apk(self):
        """
        Hardlinks/copies the APK file from Apk if it does not exist, yet.

        This is the reverse of what happens in _attach_apk()
        """
        if self.file:
            return  # there's a file already, so nothing to do here

        # create the link/copy from source to target APK
        source = self.apk.file.name
        target = get_apk_file_path(self, os.path.basename(self.apk.file.name))
        target = self.apk.file.storage.link(source, target)

        # store the target filename in this pointer
        self.file.name = target
        self.save()

maker/views/apk.py
from django.forms import ModelForm
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import CreateView, DeleteView

from maker.models import ApkPointer
from .repository import RepositoryAuthorizationMixin


class ApkForm(ModelForm):
    class Meta:
        model = ApkPointer
        # TODO allow multiple files to be uploaded at once
        fields = ['file']
        labels = {
            'file': _('Select APK file for upload'),
        }

    class Media:
        js = ('maker/js/drag-and-drop.js',)


class ApkUploadView(RepositoryAuthorizationMixin, CreateView):
    model = ApkPointer
    form_class = ApkForm

    def get(self, request, *args, **kwargs):
        # don't answer GET requests
        return HttpResponseNotFound()

    def form_valid(self, form):
        form.instance.repo = self.get_repo()
        # TODO handle multiple files to be uploaded here
        pointer = form.save()  # needed to save file to disk for scanning
        try:
            pointer.initialize()
        except Exception as e:
            pointer.delete()
            raise e

        args = [pointer.repo.pk, pointer.app.pk]
        if pointer.app.summary != '':  # app did exist already, show it
            return HttpResponseRedirect(reverse('app', args=args))
        return HttpResponseRedirect(reverse('edit_app', args=args))


class ApkPointerDeleteView(RepositoryAuthorizationMixin, DeleteView):
    model = ApkPointer
    template_name = 'maker/app/apk_delete.html'
    pk_url_kwarg = 'pk'

    def get_repo(self):
        return self.get_object().app.repo

    def get_success_url(self):
        self.get_repo().update_async()
        return reverse_lazy('edit_app', kwargs={'repo_id': self.kwargs['repo_id'],
                                                'app_id': self.kwargs['app_id']})

maker/templates/maker/repo/add.html
{% extends "maker/base_modal.html" %}
{% load i18n %}
{% load sass_tags %}

{% block title %}{% trans 'New Repo' %}{% endblock title %}


{% block rm-content %}
<div class="rm-grid--center mdl-grid">
	<div class="rm-grid--center mdl-cell mdl-cell--4-col">
		<h4 style="text-align: center">{% trans 'New Repo' %}</h4>

		<form class="rm-form mdl-grid" action="" enctype="multipart/form-data" method="post">
			{% csrf_token %}
			{% include '../form.html' %}
			<input type="submit" value="{% trans 'Create' %}"/>
		</form>
	</div>
</div>
{% endblock rm-content %}

maker/templates/maker/repo/delete.html
{% extends "maker/base_modal.html" %}
{% load i18n %}

{% block title %}{% trans 'Delete Repo' %}{% endblock %}

{% block rm-content %}
<div class="rm-form mdl-grid rm-grid--center">
	<div class="mdl-cell mdl-cell--6-col center">
		<p>
			{% blocktrans with repo=object trimmed %}
			Are you sure you want to delete the repo <strong>{{ repo }}</strong>?
			{% endblocktrans %}
		</p>
		<p class="error">
			{% blocktrans trimmed %}
			This will also delete all apps and other files from your repo.
			You will not be able to get them back,
			users of your repo will not be able to use it anymore and
			not receive updates for the apps they received from you.
			There is no way to recover this repo!
			{% endblocktrans %}
		</p>
		<p>
			<b>
			{% blocktrans trimmed %}
			Please only proceed if you know what you are doing!
			{% endblocktrans %}
			</b>
		</p>
		<form action="" method="post">
			{% csrf_token %}
			<input type="submit" value="{% trans 'Yes, I want to delete the repo' %}"/>
		</form>
	</div>
</div>
{% endblock rm-content %}

maker/templates/maker/repo/edit.html
{% extends "maker/base_modal.html" %}
{% load i18n %}
{% load sass_tags %}

{% block title %}{% trans 'Edit Repo' %}{% endblock %}


{% block rm-content %}
<div class="rm-grid--center mdl-grid">
	<div class="rm-grid--center mdl-cell mdl-cell--4-col">
		<h4 style="text-align: center">{% trans 'Edit Repo' %}</h4>

		<div class="rm-form mdl-grid ">
			<form action="" enctype="multipart/form-data" method="post">
				{% csrf_token %}
				{% include '../form.html' %}
				<input type="submit" value="{% trans 'Save Changes' %}"/>
			</form>
		</div>
	</div>
</div>
{% endblock rm-content %}

maker/templates/maker/repo/index.html
{% extends "maker/base.html" %}
{% load i18n %}
{% load humanize %}
{% load sass_tags %}

{% block title %}{{ repo.name }}{% endblock %}

{% block toolbar-items-left %}
<a href="/" class="rm-toolbar-item">
	<i class="material-icons">home</i>
</a>
{% endblock toolbar-items-left %}

{% block toolbar-title %}
{{ repo.name }}
{% endblock toolbar-title %}

{% block toolbar-items-right %}
<a href="{% url 'add_repo' %}" class="rm-toolbar-item">
	<i class="material-icons">add</i>
</a>
{% endblock toolbar-items-right %}

{% block rm-content--without-margin %}
<div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
	<div class="rm-repo-tabs__tab-bar mdl-tabs__tab-bar">
		<a href="#rm-repo-panel-apps" class="rm-repo-tabs__tab mdl-tabs__tab is-active">{% trans 'Apps' %}</a>
		<a href="#rm-repo-panel-share" class="rm-repo-tabs__tab mdl-tabs__tab">{% trans 'Share' %}</a>
		<a href="#rm-repo-panel-info" class="rm-repo-tabs__tab mdl-tabs__tab">{% trans 'Info' %}</a>
	</div>

	{% include 'maker/site_notice.html' %}

	<div class="rm-repo-tabs__panels">
		<div class="mdl-tabs__panel is-active" id="rm-repo-panel-apps">
			{% include "maker/repo/index_apps.html" %}
		</div>
		<div class="mdl-tabs__panel" id="rm-repo-panel-share">
			{% include "maker/repo/index_share.html" %}
		</div>
		<div class="mdl-tabs__panel" id="rm-repo-panel-info">
			{% include "maker/repo/index_info.html" %}
		</div>
	</div>
</div>

{% endblock rm-content--without-margin %}

maker/templates/maker/repo/index_apps.html
{% load i18n %}
<div class="rm-grid--center mdl-grid mdl-cell--9-col">
	{% if request.GET.search or is_paginated %}
	<div class="rm-repo-apps-header mdl-cell mdl-cell--12-col">
		<div class="rm-repo-apps-header-search">
			<a href="#" onclick="toggleSearch()" class="rm-repo-apps-header-search-icon">
				<i class="material-icons">search</i>
			</a>
			<div id="rm-repo-apps-header-search-input"
				 class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label rm-form">
				<form action="" method="get">
					<label for="id_search" class="mdl-textfield__label">
						{% trans 'Search for apps in your repository' %}
					</label>
					<input type="text" name="search" id="id_search" class="mdl-textfield__input" value="{{ request.GET.search }}">
				</form>
			</div>
		</div>
	</div>
	{% endif %}
	{% if apps %}
	<div class="rm-repo-apps-add">
		<div id="rm-dnd-holder--apks" class="rm-repo-apps-add-locally">
			<i class="rm-repo-apps-add-locally-icon">file_upload</i>
			<div class="rm-repo-apps-add-locally-title">{% trans 'Add .apk files' %}</div>
			<!-- TODO: Make this properly translatable -->
			<div class="rm-repo-apps-add-locally-description-first rm-dng-text" hidden>
				{% trans 'Drag and drop .apk files' %}
			</div>
			<form action="{% url 'apk_upload' repo.id %}" enctype="multipart/form-data" method="post">
				{% csrf_token %}
				<div class="rm-repo-apps-add-locally-description-second">
					<span class="rm-dng-text" hidden>{% trans 'or' %}</span>
					<label for="id_file" class="rm-repo-apps-add-locally-upload-browse">
						{% trans 'browse to upload' %}
					</label>
				</div>
				<p>{{ form.file }}</p>
				<button type="submit" class="rm-button--blue mdl-js-button">
					{% trans 'Add' %}
				</button>
			</form>
		</div>
		<div id="rm-dnd-holder--apks--loading" class="rm-repo-apps-add-locally--loading" hidden>
			{% csrf_token %}
			<div class="rm-dnd-progress mdl-js-progress"></div>
			<h3 id="rm-dnd-holder--apks--loading-title" class="rm-repo-apps-add-locally--loading-title"></h3>
		</div>
		<a href="{% url 'add_app' repo.id %}" class="rm-repo-apps-add-remotely">
			<i class="rm-repo-apps-add-remotely-icon">explore</i>
			<div class="rm-repo-apps-add-remotely-title">
				{% trans 'add from repos' %}
			</div>
		</a>
	</div>
	{% for app in apps %}
		{% url 'app' repo.id app.id as url %}
		{% include "maker/widgets/app.html" with clickable=True url=url width=6 %}
	{% endfor %}
	{% else %}
	<div class="mdl-grid mdl-grid--no-spacing rm-form">
		<div id="rm-dnd-holder-2--apks"  class="rm-repo-apps-empty-add">
			<i class="rm-repo-apps-empty-add-icon">file_upload</i>
			<div class="rm-repo-apps-empty-add-title">{% trans 'Add files' %}</div>
			<!-- TODO: Make this translatable properly -->
			<div class="rm-repo-apps-empty-add-description-first rm-dng-text" hidden>
				{% trans 'Drag and drop .apk files' %}
			</div>
			<form action="{% url 'apk_upload' repo.id %}" enctype="multipart/form-data" method="post">
				{% csrf_token %}
				<div class="rm-repo-apps-empty-add-description-second">
					<span class="rm-dng-text" hidden>{% trans 'or' %}</span>
					<label for="id_file" class="rm-repo-apps-empty-add-upload-browse">
						{% trans 'browse to upload' %}
					</label>
				</div>
				<p>{{ form.file }}</p>
				<button type="submit" class="rm-button--blue mdl-button mdl-js-button">
					{% trans 'Add' %}
				</button>
			</form>
		</div>
		<div id="rm-dnd-holder-2--apks--loading" class="rm-repo-apps-empty-add--loading" hidden>
			{% csrf_token %}
			<div class="rm-dnd-progress mdl-js-progress"></div>
			<h3 id="rm-dnd-holder-2--apks--loading-title" class="rm-repo-apps-empty-add--loading-title"></h3>
		</div>
		<div class="rm-repo-apps-empty-discover">
			<i class="rm-repo-apps-empty-discover-icon">explore</i>
			<div class="rm-repo-apps-empty-discover-title">{% trans 'Discover' %}</div>
			<div class="rm-repo-apps-empty-discover-description">{% trans 'Find things to add from other repos' %}</div>
			<a href="{% url 'add_app' repo.id %}" class="rm-repo-apps-empty-discover-add rm-no-underline">
				<button type="button" class="rm-button--blue mdl-button mdl-js-button">
					{% trans 'add from repos' %}
				</button>
			</a>
		</div>
	</div>
	{% if request.POST.search %}
	<div class="rm-no-search-results">
		{% trans 'Your search did not return any results.' %}
	</div>
	{% endif %}
	{% endif %}
</div>

<script type="text/javascript">
	var rmRepoAppsHeaderSearch = document.getElementById('id_search');
	var rmRepoAppsHeaderSearchInput = document.getElementById('rm-repo-apps-header-search-input');
	if (rmRepoAppsHeaderSearch !== null && rmRepoAppsHeaderSearch.value == '') {
		rmRepoAppsHeaderSearchInput.style.display = 'none';
	}
	function toggleSearch() {
		if (rmRepoAppsHeaderSearchInput.style.display == 'none') {
			rmRepoAppsHeaderSearchInput.style.display = 'block';
			return;
		}
		rmRepoAppsHeaderSearchInput.style.display = 'none';
	}
</script>

{% include "maker/widgets/pagination.html" %}