RepoMaker/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from maker.views import media_serve
from maker.views.repository import RepositoryListView

urlpatterns = [
    url(r'^$', RepositoryListView.as_view(), name="index"),
    url(r'^repo/', include('maker.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], media_serve,
        {'document_root': settings.MEDIA_ROOT}),
]

if not settings.SINGLE_USER_MODE:
    urlpatterns += [
        url(r'^accounts/', include('allauth.urls')),
    ]

maker/urls.py
from django.conf.urls import url

from maker.models import S3Storage, SshStorage, GitStorage
from maker.views.app import AppAddView, AppDetailView, AppUpdateView, AppDeleteView, \
    AppTranslationUpdateView
from maker.views.gitstorage import GitStorageCreate, GitStorageUpdate, GitStorageDetail, \
    GitStorageDelete
from maker.views.remoterepository import RemoteRepositoryCreateView, RemoteAppCreateView
from maker.views.repository import RepositoryListView, RepositoryCreateView, RepositoryView, \
    RepositoryUpdateView, RepositoryDeleteView
from maker.views.s3storage import S3StorageCreate, S3StorageDetail, S3StorageUpdate, S3StorageDelete
from maker.views.screenshot import ScreenshotCreateView, ScreenshotDeleteView
from maker.views.sshstorage import SshStorageCreate, SshStorageUpdate, SshStorageDetail, \
    SshStorageDelete
from maker.views.apk import ApkUploadView, ApkPointerDeleteView
from . import views


urlpatterns = [
    # Repo
    url(r'^$', RepositoryListView.as_view(), name='index'),
    url(r'^add$', RepositoryCreateView.as_view(), name='add_repo'),
    url(r'^(?P<repo_id>[0-9]+)/$', RepositoryView.as_view(), name='repo'),
    url(r'^(?P<repo_id>[0-9]+)/edit/$', RepositoryUpdateView.as_view(),
        name='edit_repo'),
    url(r'^(?P<repo_id>[0-9]+)/delete/$', RepositoryDeleteView.as_view(),
        name='delete_repo'),

    # Remote Repo
    url(r'^remote/add$', RemoteRepositoryCreateView.as_view(), name='add_remote_repo'),
    url(r'^remote/(?P<remote_repo_id>[0-9]+)/update/$', views.remote_update, name='remote_update'),

    # App
    url(r'^(?P<repo_id>[0-9]+)/app/add/$', AppAddView.as_view(), name='add_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/remote/(?P<remote_repo_id>[0-9]+)/add/$',
        AppAddView.as_view(), name='add_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/add/category/(?P<category_id>[0-9]+)/$',
        AppAddView.as_view(), name='add_app_with_category'),
    url(r'^(?P<repo_id>[0-9]+)/app/remote/(?P<remote_repo_id>[0-9]+)/add/' +
        r'category/(?P<category_id>[0-9]+)/$',
        AppAddView.as_view(), name='add_app_with_category'),
    url(r'^(?P<repo_id>[0-9]+)/app/remote/(?P<remote_repo_id>[0-9]+)/add/(?P<app_id>[0-9]+)$',
        RemoteAppCreateView.as_view(), name='add_remote_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/$', AppDetailView.as_view(), name='app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/edit/$', AppUpdateView.as_view(),
        name='edit_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/delete/$', AppDeleteView.as_view(),
        name='delete_app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/translate/$',
        AppTranslationUpdateView.as_view(), name='app_translate'),

    # App Screenshots
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/screenshot/add/$',
        ScreenshotCreateView.as_view(), name='screenshot_add'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/screenshot/(?P<s_id>[0-9]+)/delete/$',
        ScreenshotDeleteView.as_view(), name='screenshot_delete'),

    # Apks
    url(r'^(?P<repo_id>[0-9]+)/app/apk/upload/$', ApkUploadView.as_view(), name='apk_upload'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/apk/(?P<pk>[0-9]+)/delete/$',
        ApkPointerDeleteView.as_view(), name='apk_delete'),

    # Repo Operations
    url(r'^(?P<repo_id>[0-9]+)/update/$$', views.update, name='update'),
    url(r'^(?P<repo_id>[0-9]+)/publish/$$', views.publish, name='publish'),

    # S3 Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/add/$',
        S3StorageCreate.as_view(), name=S3Storage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/$',
        S3StorageDetail.as_view(), name=S3Storage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/edit/$',
        S3StorageUpdate.as_view(), name=S3Storage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/delete/$',
        S3StorageDelete.as_view(), name=S3Storage.delete_url_name),

    # SSH Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/add/$',
        SshStorageCreate.as_view(), name=SshStorage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/$',
        SshStorageDetail.as_view(), name=SshStorage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/edit/$',
        SshStorageUpdate.as_view(), name=SshStorage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/delete/$',
        SshStorageDelete.as_view(), name=SshStorage.delete_url_name),

    # Git Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/git/add/$',
        GitStorageCreate.as_view(), name=GitStorage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/$',
        GitStorageDetail.as_view(), name=GitStorage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/edit/$',
        GitStorageUpdate.as_view(), name=GitStorage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/delete/$',
        GitStorageDelete.as_view(), name=GitStorage.delete_url_name),
]

maker/models/screenshot.py
import logging
import os
from io import BytesIO

import requests
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

from maker import tasks
from maker.storage import get_screenshot_file_path, RepoStorage
from .app import RemoteApp, App

PHONE = 'phoneScreenshots'
SEVEN_INCH = 'sevenInchScreenshots'
TEN_INCH = 'tenInchScreenshots'
TV = 'tvScreenshots'
WEAR = 'wearScreenshots'
TYPE_CHOICES = (
    (PHONE, 'Phone'),
    (SEVEN_INCH, "7'' Tablet"),
    (TEN_INCH, "10'' Tablet"),
    (TV, 'TV'),
    (WEAR, 'Wearable'),
)


class AbstractScreenshot(models.Model):
    language_code = models.CharField(max_length=32, default='en')
    type = models.CharField(max_length=32, choices=TYPE_CHOICES, default=PHONE)

    def __str__(self):
        return self.app.__str__() + " - " + self.language_code + " " + self.type

    def get_url(self):
        raise NotImplementedError()

    class Meta:
        abstract = True


class Screenshot(AbstractScreenshot):
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    file = models.ImageField(upload_to=get_screenshot_file_path, storage=RepoStorage(),
                             max_length=1024)
    # TODO add a thumbnail to be automatically generated from file

    def __str__(self):
        return super(Screenshot, self).__str__() + " " + self.file.name

    def get_relative_path(self):
        return os.path.join(self.app.package_id, self.language_code, self.type)

    def get_url(self):
        return self.file.url


class RemoteScreenshot(AbstractScreenshot):
    app = models.ForeignKey(RemoteApp, on_delete=models.CASCADE)
    url = models.URLField(max_length=2048)

    def __str__(self):
        return super(RemoteScreenshot, self).__str__() + " " + os.path.basename(self.url)

    def get_url(self):
        return self.url

    @staticmethod
    def add(locale, s_type, app, base_url, files):
        """
        Creates and saves one or more new RemoteScreenshots if the given s_type is supported.
        """
        if not is_supported_type(s_type):
            return
        for file in files:
            url = base_url + file
            if not RemoteScreenshot.objects.filter(language_code=locale, type=s_type, app=app,
                                                   url=url).exists():
                screenshot = RemoteScreenshot(language_code=locale, type=s_type, app=app, url=url)
                screenshot.save()

    def download_async(self, app):
        """
        Downloads this RemoteScreenshot asynchronously and creates a local Screenshot if successful.
        """
        tasks.download_remote_screenshot(self.pk, app.pk)

    def download(self, app_id):
        """
        Does a blocking download of this RemoteScreenshot
        and creates a local Screenshot if successful.
        """
        screenshot = Screenshot(language_code=self.language_code, type=self.type, app_id=app_id)
        r = requests.get(self.url)
        if r.status_code == requests.codes.ok:
            screenshot.file.save(os.path.basename(self.url), BytesIO(r.content), save=True)


def is_supported_type(s_type):
    for t in TYPE_CHOICES:
        if s_type == t[0]:
            return True
    return False


@receiver(post_delete, sender=Screenshot)
def screenshot_post_delete_handler(**kwargs):
    apk = kwargs['instance']
    logging.info("Deleting Screenshot: %s", apk.file.name)
    apk.file.delete(save=False)

maker/views/apk.py
from django.forms import ModelForm
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import CreateView, DeleteView

from maker.models import ApkPointer
from .repository import RepositoryAuthorizationMixin


class ApkForm(ModelForm):
    class Meta:
        model = ApkPointer
        # TODO allow multiple files to be uploaded at once
        fields = ['file']
        labels = {
            'file': _('Select APK file for upload'),
        }

    class Media:
        js = ('maker/js/drag-and-drop.js',)


class ApkUploadView(RepositoryAuthorizationMixin, CreateView):
    model = ApkPointer
    form_class = ApkForm

    def get(self, request, *args, **kwargs):
        # don't answer GET requests
        return HttpResponseNotFound()

    def form_valid(self, form):
        form.instance.repo = self.get_repo()
        # TODO handle multiple files to be uploaded here
        pointer = form.save()  # needed to save file to disk for scanning
        try:
            pointer.initialize()
        except Exception as e:
            pointer.delete()
            raise e

        args = [pointer.repo.pk, pointer.app.pk]
        if pointer.app.summary != '':  # app did exist already, show it
            return HttpResponseRedirect(reverse('app', args=args))
        return HttpResponseRedirect(reverse('edit_app', args=args))


class ApkPointerDeleteView(RepositoryAuthorizationMixin, DeleteView):
    model = ApkPointer
    template_name = 'maker/app/apk_delete.html'
    pk_url_kwarg = 'pk'

    def get_repo(self):
        return self.get_object().app.repo

    def get_success_url(self):
        self.get_repo().update_async()
        return reverse_lazy('edit_app', kwargs={'repo_id': self.kwargs['repo_id'],
                                                'app_id': self.kwargs['app_id']})

maker/views/gitstorage.py
import fdroidserver.index
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.forms import CharField, URLField
from django.utils.translation import ugettext_lazy as _

from maker.models.storage import GitStorage, HostnameValidator, PathValidator
from .sshstorage import SshStorageForm, SshKeyMixin
from .storage import StorageCreateView, StorageUpdateView, StorageDeleteView, StorageDetailView


class GitStorageForm(SshStorageForm):
    ssh_url = CharField(required=True, label=_('Git Repository SSH Address'))
    url = URLField(required=False, label=_('Raw Git URL'), help_text=_(
        'This is the location where the uploaded files can be accessed from' +
        ' in raw form.' +
        ' Leave empty for GitHub or GitLab.com repositories.'))

    def get_initial_for_field(self, field, field_name):
        if field_name == 'ssh_url' and self.instance.pk:
            return self.instance.get_remote_url()
        return super(GitStorageForm, self).get_initial_for_field(field, field_name)

    class Meta(SshStorageForm.Meta):
        model = GitStorage
        fields = ['ssh_url', 'url']


class GitUrlValidationMixin(SshKeyMixin):

    def form_valid(self, form):
        # check that ssh_url starts with git@
        if not form.cleaned_data['ssh_url'].startswith('git@'):
            form.add_error('ssh_url', _("This URL must start with 'git@'."))
            return self.form_invalid(form)

        # strip the standard git user name from the URL
        ssh_url = form.cleaned_data['ssh_url'].replace('git@', '')

        # check that ssh_url ends with .git
        if not ssh_url.endswith('.git'):
            form.add_error('ssh_url', _("This URL must end with '.git'."))
            return self.form_invalid(form)

        # strip the .git ending from the URL
        ssh_url = ssh_url.replace('.git', '')

        # check that ssh_url includes a path
        url_error = _("This URL is invalid. Please copy the exact SSH URL of your git repository.")
        if ':' not in ssh_url:
            form.add_error('ssh_url', url_error)
            return self.form_invalid(form)

        # extract hostname and path from URL
        (hostname, path) = ssh_url.split(':', 1)

        # validate hostname and path
        try:
            HostnameValidator().__call__(hostname)
            PathValidator().__call__('/' + path)
        except ValidationError:
            form.add_error('ssh_url', url_error)
            return self.form_invalid(form)

        # assign hostname and path to the GitStorage object
        form.instance.host = hostname
        form.instance.path = path

        # try to generate the F-Droid repo URL from the git repo URL
        url = fdroidserver.index.get_mirror_service_url(form.cleaned_data['ssh_url'])
        if url is not None:
            form.instance.url = url
        # URL generation failed, so the user needs to provide a valid URL
        else:
            try:
                URLValidator().__call__(form.cleaned_data['ssh_url'])
            except ValidationError:
                form.add_error('url', _('Please add a valid URL' +
                                        'for the raw content of this git repository.'))
                return self.form_invalid(form)

        return super(GitUrlValidationMixin, self).form_valid(form)


class GitStorageCreate(GitUrlValidationMixin, StorageCreateView):
    model = GitStorage
    form_class = GitStorageForm
    template_name = 'maker/storage/form_git.html'


class GitStorageUpdate(GitUrlValidationMixin, StorageUpdateView):
    model = GitStorage
    form_class = GitStorageForm


class GitStorageDetail(StorageDetailView):
    model = GitStorage
    template_name = 'maker/storage/detail_git.html'


class GitStorageDelete(StorageDeleteView):
    model = GitStorage

maker/views/s3storage.py
from django.forms import PasswordInput
from django.utils.translation import ugettext_lazy as _

from maker.models import S3Storage
from .storage import StorageForm, StorageCreateView, StorageDetailView, StorageUpdateView, \
    StorageDeleteView


class S3StorageForm(StorageForm):

    class Meta(StorageForm.Meta):
        model = S3Storage
        fields = ['region', 'bucket', 'accesskeyid', 'secretkey']
        labels = {
            'bucket': _('Bucket Name'),
            'accesskeyid': _('Access Key ID'),
            'secretkey': _('Secret Access Key'),
        }
        help_texts = {
            'region': _('Other regions are currently not supported.'),
        }
        widgets = {
            'secretkey': PasswordInput(),
        }


class S3StorageCreate(StorageCreateView):
    model = S3Storage
    form_class = S3StorageForm


class S3StorageUpdate(StorageUpdateView):
    model = S3Storage
    form_class = S3StorageForm


class S3StorageDetail(StorageDetailView):
    model = S3Storage
    template_name = 'maker/storage/detail_s3.html'


class S3StorageDelete(StorageDeleteView):
    model = S3Storage

maker/views/screenshot.py
from django.conf import settings
from django.forms import Select
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, DeleteView

from maker.models import Screenshot
from maker.views.repository import RepositoryAuthorizationMixin
from . import BaseModelForm


class ScreenshotForm(BaseModelForm):
    class Meta:
        model = Screenshot
        fields = ['language_code', 'type', 'file']
        labels = {
            'language_code': _('Language'),
            'file': _('Select Screenshot for upload'),
        }
        widgets = {
            'language_code': Select(choices=settings.LANGUAGES)
        }


class ScreenshotCreateView(RepositoryAuthorizationMixin, CreateView):
    model = Screenshot
    form_class = ScreenshotForm
    template_name = "maker/app/screenshot_add.html"

    def form_valid(self, form):
        form.instance.app_id = self.kwargs['app_id']
        result = super(ScreenshotCreateView, self).form_valid(form)
        self.get_repo().update_async()
        return result

    def get_success_url(self):
        return reverse('app', args=[self.object.app.repo.pk, self.object.app.pk])


class ScreenshotDeleteView(RepositoryAuthorizationMixin, DeleteView):
    model = Screenshot
    pk_url_kwarg = 's_id'
    template_name = 'maker/app/screenshot_delete.html'

    def get_repo(self):
        return self.get_object().app.repo

    def get_success_url(self):
        self.get_repo().update_async()
        return reverse_lazy('edit_app', kwargs={'repo_id': self.kwargs['repo_id'],
                                                'app_id': self.kwargs['app_id']})

maker/templates/maker/app/apk_delete.html
{% extends "maker/base_modal.html" %}
{% load i18n %}
{% load sass_tags %}

{% block title %}{% trans 'Delete App Version' %}{% endblock %}

{% block rm-content %}
<div class="rm-form mdl-grid rm-grid--center">
	<div class="mdl-cell mdl-cell--6-col center">
		<p>
			{% blocktrans with app=object.app version=object.apk.version_name code=object.apk.version_code trimmed %}
			Are you sure you want to delete this version <strong>{{ version }}</strong> ({{ code }})
			from your app <strong>{{ app }}</strong>?
			{% endblocktrans %}
		</p>
		<form action="" method="post">
			{% csrf_token %}
			<input type="submit" value="{% trans 'Confirm' %}"/>
		</form>
	</div>
</div>
{% endblock rm-content %}

maker/templates/maker/app/delete.html
{% extends "maker/base_modal.html" %}
{% load i18n %}
{% load sass_tags %}

{% block title %}{% trans 'Delete App' %}{% endblock %}

{% block rm-content %}
<div class="rm-form mdl-grid rm-grid--center">
    <div class="mdl-cell mdl-cell--6-col center">
        <p>
            {% blocktrans with app=object.app %}
            Are you sure you want to delete your app <strong>{{ object }}</strong>?
            {% endblocktrans %}
        </p>
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Confirm' %}"/>
        </form>
    </div>
</div>
{% endblock rm-content %}

maker/templates/maker/app/index.html
{% extends "maker/base_modal.html" %}
{% load i18n %}
{% load humanize %}

{% block title %}{{ app.name }}{% endblock title %}

{% block toolbar %}
<div class="rm-grid--full-width rm-grid--center mdl-grid">
	<div class="rm-app-toolbar mdl-cell mdl-cell--8-col">
		{% block back-button %}
		<a href="{% url 'repo' app.repo.id %}" class="rm-toolbar-action-left">
			<i class="material-icons">arrow_back</i>
		</a>
		{% endblock back-button %}
		<div>
			{% block top-buttons %}
			<span class="rm-toolbar-item">
				<!-- TODO enable after user tests
				<a href="{% url 'app_translate' app.repo.id app.id %}" class="rm-no-underline">
				-->
				{% blocktrans with count=app.get_available_languages.count trimmed %}
				Language ({{ count }})
				{% endblocktrans %}
				<!--
				</a>
				-->
				<i class="material-icons">expand_more</i>
				<!-- TODO: Make Language dropdown working
				{% trans 'None' as None %}
				{{ app.get_available_language_names|join:", "|default:None }}
				-->
			</span>
			<a href="{% url 'edit_app' app.repo.id app.id %}" class="rm-no-underline">
				<button class="rm-button mdl-button mdl-js-button">
					{% trans 'Edit' %}
				</button>
			</a>
			{% endblock top-buttons %}
		</div>
	</div>
</div>
{% endblock toolbar %}

{% block rm-content %}
<div class="rm-grid--center mdl-grid">
	<div class="mdl-cell mdl-cell--6-col">
		<div class="rm-app-header">
			<img src="{{ app.icon.url }}" alt="Repo Icon" class="rm-icon"/>
			<div class="rm-app-primary-content">
				<h2 class="rm-app-title">{{ app.name }}</h2>
				{% block author %}
				{% if app.author_name %}
				<div class="rm-app-author">
					{% blocktrans with author=app.author_name trimmed %}
					Developed by {{ author }}
					{% endblocktrans %}
				</div>
				{% endif %}
				{% endblock author %}
			</div>
			<div class="rm-app-secondary-content">
				{% if app.get_latest_version %}
				<div class="rm-app-version">
					Version: {{ app.get_latest_version.version_name }}
				</div>
				{% endif %}
				<div class="rm-app-last-time-updated">
					{# time is e.g. '6 days' and will be translated automatically #}
					{% blocktrans with time=app.last_updated_date|timesince trimmed %}
					Updated {{ time }} ago
					{% endblocktrans %}
				</div>
			</div>
		</div>
		<div class="rm-app-summary-category">
			<div class="rm-app-summary">{% block summary %}{{ app.summary }}{% endblock summary %}</div>
			{% block categories %}
			{% if app.category.exists %}
			{% for category in app.category.all %}
			<span class="rm-app-category-chip mdl-chip">
				<span class="rm-app-category-text mdl-chip__text">{{ category }}</span>
			</span>
			{% endfor %}
			{% endif %}
			{% endblock categories %}
		</div>
	</div>
</div>
{% if form or app.screenshot_set.exists %}
<div class="rm-grid--center mdl-grid">
	<div class="rm-app-screenshots mdl-cell mdl-cell--8-col">
		{% block screenshot-drop %}{% endblock screenshot-drop %}
		{% for screenshot in app.screenshot_set.all %}
		<div class="rm-app-screenshot">
			{% block screenshot-delete %}{% endblock screenshot-delete %}
			<img src="{{ screenshot.get_url }}"/>
		</div>
		{% endfor %}
	</div>
</div>
{% endif %}
<div class="rm-grid--center mdl-grid">
	<div class="rm-app-description mdl-cell mdl-cell--6-col">
		{% block description %}
		{{ app.description|safe }}
		{% endblock description %}
	</div>
</div>
<div class="rm-grid--center mdl-grid">
	<div class="rm-app-versions mdl-cell mdl-cell--6-col">
		<h4 class="rm-app-versions-title">
			{% trans 'version history' %}
		</h4>
		{% block apk-drop %}{% endblock apk-drop %}
		{% if apks %}
		<ul class="rm-app-versions-list mdl-list">
			{% for pointer in apks %}
			<li class="rm-app-versions-item mdl-list__item mdl-list__item--two-line">
				<span class="mdl-list__item-primary-content">
					<span>
						{% blocktrans with version=pointer.apk.version_name code=pointer.apk.version_code trimmed %}
						Version {{ version }} ({{ code }})
						{% endblocktrans %}
					</span>
					{% if pointer.file %}
					<span class="mdl-list__item-sub-title">
						{% blocktrans with date=pointer.apk.added_date|date:"DATE_FORMAT" trimmed %}
						Released {{ date }}
						{% endblocktrans %}
					</span>
					{% else %}
					<span class="mdl-list__item-sub-title">
						<!-- TODO: Use progress bar instead and reload when download done -->
						{% trans 'APK is still downloading...' %}
					</span>
					{% endif %}
				</span>
				{% block apk-delete %}{% endblock apk-delete %}
			</li>
			{% endfor %}
		</ul>
		{% else %}
		<p>{% trans 'This app has no APK files.' %}</p>
		<p>{% trans 'If you added this app from a remote repo, try deleting it and adding it again.' %}</p>
		{% endif %}
	</div>
</div>
<div class="rm-app-navigation mdl-grid">
	<div class="mdl-cell mdl-cell--6-col">
	{% if app.get_previous %}
	<a href="{% block prev-url %}{{ app.get_previous.get_absolute_url }}{% endblock %}"
	   class="rm-app-navigation-previous">
		<i class="material-icons">arrow_back</i>
		<h3 class="rm-app-navigation-previous-text">{% trans 'Previous' %}</h3>
	</a>
	{% endif %}
	</div>
	<div class="mdl-cell mdl-cell--6-col">
	{% if app.get_next %}
	<a href="{% block next-url %}{{ app.get_next.get_absolute_url }}{% endblock %}"
	   class="rm-app-navigation-next">
		<i class="material-icons">arrow_forward</i>
		<h3 class="rm-app-navigation-next-text">{% trans 'Next' %}</h3>
	</a>
	{% endif %}
	</div>
</div>
{% block page-footer %}{% endblock page-footer %}
{% endblock rm-content %}

maker/templates/maker/app/remote_add.html
{% extends "maker/base.html" %}
{% load i18n %}
{% load sass_tags %}

{% block title %}{% trans 'Add App' %}{% endblock %}


{% block rm-content %}
<div class="mdl-grid rm-grid--full-width rm-grid--center">
	<div class="mdl-cell mdl-cell--8-col" style="text-align:center">
		<h2>
			{% blocktrans with app=app.name repo=repo.name trimmed %}
			Add {{ app }} to {{ repo }}
			{% endblocktrans %}
		</h2>

		{% if app.summary %}
		<p>{{ app.summary }}</p>
		{% endif %}

		<p>{{ app.description|safe }}</p>
	</div>
</div>

<p></p>

<div class="rm-form">
	<form action="" enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{% include '../form.html' %}
		<input type="submit" value="{% blocktrans with repo=repo.name %}Add App to {{ repo }}{% endblocktrans %}"/>
	</form>
</div>

<p></p>
{% endblock rm-content %}

maker/templates/maker/app/screenshot_add.html
{% extends "maker/base.html" %}
{% load i18n %}
{% load sass_tags %}

{% block title %}{% trans 'Add Screenshot' %}{% endblock %}


{% block rm-content %}

<h1>{% trans 'Add Screenshot' %}</h1>

<div class="rm-form">
	<form action="" enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{% include '../form.html' %}
		<div class="mdl-cell mdl-cell--6-col">
			<input type="submit" value="{% trans 'Upload Screenshot' %}"/>
		</div>
	</form>
</div>

<p></p>

{% endblock rm-content %}